import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Cabin } from "next/font/google";
import "./globals.css";
import BrandLoader from "@/components/features/motion/page";
import Header from "@/components/common/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const cabin = Cabin({
  variable: "--font-cabin", // Creates a CSS variable for the font
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Customize font weights
});

export const metadata: Metadata = {
  title: "Abhishek Pundir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${cabin.variable}  antialiased`}
      >
        <BrandLoader>
          <Header />
          <div className="mt-20 px-2 py-1 md:px-2 lg:px-4" >{children}</div>
        </BrandLoader>
      </body>
    </html>
  );
}
